# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Starting Pipeline'
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift Connection'
    cmd: 'status'
    uselocalOc: true
  displayName: 'Check OpenShift Connection'
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift Connection'
    cmd: 'start-build pytest-calculator --wait --follow'
    uselocalOc: true
  displayName: 'Start the Build'
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift Connection'
    cmd: 'rollout latest dc/pytest-calculator'
    uselocalOc: true
  displayName: 'Rollout latest build'
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift Connection'
    cmd: 'rollout status dc pytest-calculator'
    uselocalOc: true
  displayName: 'Check rollout status'
- task: oc-setup@3
  inputs:
    openshiftService: 'Openshift Connection'
    version: '4.3'
  displayName: 'Find Pod Name'
- script: |
    sleep 80
    echo "Waiting for pod redeployment"
    echo "##vso[task.setvariable variable=POD_NAME]`oc get pods -l app=pytest-calculator -o jsonpath='{range .items[0].metadata}{.name}{"\n"}{end}'`"
